### ISSUE TITLE
Proposal TODO T-Minus 4 days.

### ISSUE THREAD

**Issue by jibbajab** [the-babylon-project/FooFlighters#16]
- [ ] Working snapshat of 3 .glb or .gltf models in place of sphere. (video or ss)
- [ ]  Example Store View (screen shot).
- [ ] Gameplay snippet. (video).
- [ ] Wireframes (can be hand sketched if necessary) for any undone GUIS (main menu/match making) (ss of stately may work, but may not render well...maybe show, and link)
- [ ] Proposal writing and fact-finding.
